workflow updates

diff --git a/.github/workflows/webapp-build-ci.yml b/.github/workflows/webapp-build-ci.yml
--- a/.github/workflows/webapp-build-ci.yml
+++ b/.github/workflows/webapp-build-ci.yml
@@ -53,8 +53,23 @@ jobs:
 
     # Format Packer template
     - name: Format Packer template
-      run: packer fmt webapp.pkr.hcl
+      id: fmt
+      run: packer fmt -check -diff .
+      continue-on-error: true
 
     # Validate Packer template
     - name: Validate Packer template
+      id: validate                                        
       run: packer validate webapp.pkr.hcl
+
+    - name: Check packer fmt results
+      if: steps.fmt.outcome == 'failure'
+      run: |
+        echo "Packer template is not properly formatted. Please run 'packer fmt' and commit the changes."
+        exit 1
+
+    - name: Check packer validate results
+      if: steps.validate.outcome == 'failure'
+      run: |
+        echo "Packer template validation failed. Please fix the errors and try again."
+        exit 1
